# Generated by Django 5.0.4 on 2024-05-06 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('cell', models.CharField(max_length=25)),
                ('national_id', models.CharField(max_length=20)),
                ('dob', models.DateField()),
                ('address', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('occupation', models.CharField(max_length=100)),
                ('marital_status', models.CharField(choices=[('S', 'Single'), ('M', 'Married'), ('D', 'Divorced'), ('W', 'Widowed'), ('P', 'Separated')], max_length=1)),
                ('emergency_contact_name', models.CharField(blank=True, max_length=255, null=True)),
                ('emergency_contact_phone', models.CharField(blank=True, max_length=25, null=True)),
                ('passport_number', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receive_news', models.BooleanField(default=True)),
                ('receive_promotions', models.BooleanField(default=True)),
                ('receive_alerts', models.BooleanField(default=True)),
                ('receive_transaction_message', models.BooleanField(default=True)),
                ('receive_pin_change_alert', models.BooleanField(default=True)),
                ('receive_email', models.BooleanField(default=True)),
                ('receive_sms', models.BooleanField(default=True)),
                ('receive_phone_call', models.BooleanField(default=True)),
                ('receive_product_recommendations', models.BooleanField(default=True)),
                ('receive_discount_offers', models.BooleanField(default=True)),
                ('receive_exclusive_deals', models.BooleanField(default=True)),
                ('receive_account_balance_alerts', models.BooleanField(default=True)),
                ('receive_transaction_notifications', models.BooleanField(default=True)),
                ('receive_fraud_alerts', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('account_number', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('branch_code', models.CharField(max_length=230)),
                ('currency', models.CharField(max_length=230)),
                ('pin', models.CharField(max_length=4)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=50)),
                ('account_type', models.CharField(choices=[('savings', 'Savings'), ('checking', 'Checking'), ('investment', 'Investment'), ('credit', 'Credit')], default='checking', max_length=20)),
                ('account_status', models.CharField(choices=[('active', 'Active'), ('frozen', 'Frozen'), ('closed', 'Closed')], default='active', max_length=20)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('beneficiary_designations', models.ManyToManyField(blank=True, related_name='beneficiary_accounts', to='core.personalinfo')),
                ('joint_account_holders', models.ManyToManyField(blank=True, related_name='joint_accounts', to='core.personalinfo')),
                ('personal_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.personalinfo')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(max_length=230)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=50)),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdrawal', 'Withdrawal'), ('transfer', 'Transfer')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='core.account')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='core.account')),
            ],
        ),
    ]
